[book]
title = "The OrbTk Book"
description = "The Orbital Widget Toolkit (OrbTk)is a multi platform toolkit, that enables you to build scalable user interfaces. All components are devoloped with the programming language Rust."
authors = [
	"Florian Blasius <flovanpt@posteo.de>",
	"Ralf Zerres <ralf.zerres.de@gmail.com>",
	"with Contributions from the Rust Community"
]
language = "en"

[rust]
edition = "2021"

[build]
create-missing = false

[output.html]
additional-css = ["ferries.css", "theme/2020-edition.css"]
additional-js = ["ferries.js", "mermaid.min.js", "mermaid-init.js"]
cname = "orbtk-book.rs"
copy-fonts = true
curly-quotes = true
default-theme = "light"
edit-url-template = "https://github.com/redox-os/orbtk-book/tree/main/book/{path}"
git-repository-url = "https://github.com/redox-os/orbtk-book/tree/main/book"
git-repository-icon = "fa-github"
input-404 = "en/404.md"
prefered-dark-theme = "navy"
mathjax-support = true
#site-url = "/orbtk-book/"
#theme = "navy"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
line-numbers = true

[output.html.redirect]
"/format/config.html" = "configuration/index.html"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.linkcheck]
## Should we check links on the internet? Enabling this option adds a
## non-negligible performance impact
#follow-web-links = false

## Are we allowed to link to files outside of the book's root directory? This
## may help prevent linking to sensitive files (e.g. "../../../../etc/shadow")
#traverse-parent-directories = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[language.en]
name = "English"

[language.de]
name = "Deutsch"
title = "Das OrbTk Book"
description = "Das Orbital Widget Toolkit (OrbTk) ist eine Multi-Pallform Toolkit zur Erstellung skalierbarer Benutzeroberflächen. Alle Komponenten wurden nativ in der Programmiersprache Rust entwickelt."

[language.es]
name = "Español"

[language.fr]
name = "Français"
